name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - stg
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_PASSWORD }}" | docker login myregistry.azurecr.io -u "${{ secrets.AZURE_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push myregistry.azurecr.io/myapp:${{ github.sha }}

  deploy_stg:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/stg'
    steps:
      - name: Deploy to Azure - Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myapp-staging'
          slot-name: 'staging'
          images: 'myregistry.azurecr.io/myapp:${{ github.sha }}'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_STG }}

  deploy_prd:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Azure - Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myapp-production'
          slot-name: 'production'
          images: 'myregistry.azurecr.io/myapp:${{ github.sha }}'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PRD }}
